### ISSUE TITLE
aurelia-cli: Dependency trace fails when the require() target is a directory

### ISSUE THREAD

**Issue by kkagamida** [aurelia/documentation#280]
**I'm submitting a bug report**

* **Library Version:**
0.19.0

**Please tell us about your environment:**
* **Operating System:**
Windows Server 2012 R2

* **Node Version:**
6.5.0

* **NPM Version:**
3.10.3

* **JSPM OR Webpack AND Version**
JSPM 0.16.45

* **Browser:**
Chrome 53

* **Language:**
ESNext

**Current behavior:**
When executing **au run**, an error occurs during the dependency trace when the target of a call to require() is a directory.

This behavior became apparent when trying to use the mongodb package. The index.js file contains the line:

    connect.GridFSBucket = require('./lib/gridfs-stream');

where gridfs-stream is a directory.

To reproduce the error:
* Create a new project using **au new**.
* Create a "test" directory under "src".
* Add the line "var test = require('./test');" to app.js.
* Start the app using **au run**.

The attached zip file can be used if desired.  Extract into the src directory.
[src.zip](https://github.com/aurelia/documentation/files/468664/src.zip)

Example output:

    Tracing app...
    { uid: 9,
      name: 'writeBundles',
      branch: false,
      error:
       { Error: ENOENT: no such file or directory, open 'C:\dev\aurelia-cli-bug\src\
    test.js'
           at Error (native)
           at Object.fs.openSync (fs.js:640:18)
           at Object.fs.readFileSync (fs.js:508:33)
           at Object.exports.readFileSync (C:\dev\aurelia-cli-bug\node_modules\aurel
    ia-cli\lib\file-system.js:38:13)
           at fileRead (C:\dev\aurelia-cli-bug\node_modules\aurelia-cli\lib\build\bu
    ndled-source.js:83:31)
           at Object.context.fileRead (C:\dev\aurelia-cli-bug\node_modules\aurelia-c
    li\lib\build\amodro-trace\lib\loader\Loader.js:176:18)
           at Object.context.load (C:\dev\aurelia-cli-bug\node_modules\aurelia-cli\l
    ib\build\amodro-trace\lib\loader\Loader.js:357:30)
           at Object.load (eval at <anonymous> (C:\dev\aurelia-cli-bug\node_modules\
    aurelia-cli\lib\build\amodro-trace\lib\loader\Loader.js:14:9), <anonymous>:832:29)
           at Object.fetch (eval at <anonymous> (C:\dev\aurelia-cli-bug\node_modules
    \aurelia-cli\lib\build\amodro-trace\lib\loader\Loader.js:14:9), <anonymous>:822:66)
           at Object.check (eval at <anonymous> (C:\dev\aurelia-cli-bug\node_modules
    \aurelia-cli\lib\build\amodro-trace\lib\loader\Loader.js:14:9), <anonymous>:854:30)
         errno: -4058,
         code: 'ENOENT',
         syscall: 'open',
         path: 'C:\\dev\\aurelia-cli-bug\\src\\test.js',
         moduleTree: [ 'app' ],
         fileName: 'C:/dev/aurelia-cli-bug/src/app.js' },
      duration: [ 0, 41572159 ],
      time: 1473727816150 }

**Expected/desired behavior:**

* **What is the expected behavior?**
According to the node.js documentation, having a directory as the target of require() is allowed, so the dependency trace should not assume that the target is a .js file.

* **What is the motivation / use case for changing the behavior?**
To be able to install modules such as mongodb without having to modify the module code.

**Comment by EisenbergEffect** [comment]
Can you try setting up a dependency issue in the aurelia.json file for the gridfs-stream project? That may solve the problem.

**Comment by kkagamida** [comment]
I hope that I understood what you wanted me to do.  I'm new to Aurelia.

I added the following to the "dependencies" array in aurelia.json:

          {
            "name": "gridfs-stream",
            "path": "../node_modules/mongodb/lib/gridfs-stream",
            "main": "index"
          },
          {
            "name": "mongodb",
            "path": "../node_modules/mongodb",
            "main": "index",
            "deps": [
              "es6-promise",
              "gridfs-stream",
              "mongodb-core",
              "readable-stream"
            ],
            "resources": [
              "lib/*.js",
              "lib/bulk/*.js",
              "lib/gridfs/*.js"
            ]
          }

Got the following error:

    Starting 'writeBundles'...
    Tracing app...
    Tracing contact-detail...
    error C:\dev\aurelia_contact\contact-manager\node_modules\util.js
    error C:\dev\aurelia_contact\contact-manager\node_modules\crypto.js
    error C:\dev\aurelia_contact\contact-manager\node_modules\fs\index.js
    error C:\dev\aurelia_contact\contact-manager\node_modules\mongodb\node_modules\r
    eadable-stream.js
    error C:\dev\aurelia_contact\contact-manager\node_modules\mongodb\node_modules\es6-promise.js
    error C:\dev\aurelia_contact\contact-manager\node_modules\hbo-dnsd.js
    error C:\dev\aurelia_contact\contact-manager\node_modules\native-dns.js
    { uid: 9,
      name: 'writeBundles',
      branch: false,
      error:
           { Error: ENOENT: no such file or directory, open 'C:\dev\aurelia_contact\contact-manager\node_modules\mongodb\lib\gridfs-stream.js'
           at Error (native)
           at Object.fs.openSync (fs.js:640:18)
           at Object.fs.readFileSync (fs.js:508:33)
           at Object.exports.readFileSync (C:\dev\aurelia_contact\contact-manager\node_modules\aurelia-cli\lib\file-system.js:38:13)
           at fileRead (C:\dev\aurelia_contact\contact-manager\node_modules\aurelia-cli\lib\build\bundled-source.js:83:31)
           at Object.context.fileRead (C:\dev\aurelia_contact\contact-manager\node_modules\aurelia-cli\lib\build\amodro-trace\lib\loader\Loader.js:176:18)
           at Object.context.load (C:\dev\aurelia_contact\contact-manager\node_modules\aurelia-cli\lib\build\amodro-trace\lib\loader\Loader.js:357:30)
           at Object.load (eval at <anonymous> (C:\dev\aurelia_contact\contact-manager\node_modules\aurelia-cli\lib\build\amodro-trace\lib\loader\Loader.js:14:9), <anonymous>:832:29)
           at Object.fetch (eval at <anonymous> (C:\dev\aurelia_contact\contact-manager\node_modules\aurelia-cli\lib\build\amodro-trace\lib\loader\Loader.js:14:9),<anonymous>:822:66)
           at Object.check (eval at <anonymous> (C:\dev\aurelia_contact\contact-manager\node_modules\aurelia-cli\lib\build\amodro-trace\lib\loader\Loader.js:14:9),<anonymous>:854:30)
         errno: -4058,
         code: 'ENOENT',
         syscall: 'open',
         path: 'C:\\dev\\aurelia_contact\\contact-manager\\node_modules\\mongodb\\lib\\gridfs-stream.js',
         moduleTree: [ 'mongodb/index' ],
         fileName: 'C:/dev/aurelia_contact/contact-manager/node_modules/mongodb/index.js' },
      duration: [ 1, 703560375 ],
      time: 1475261073859 }

My team was experimenting with Aurelia, but due to time constraints we've had to move on. Unfortunately I won't be able to devote any more time to this, so I'm closing this issue.
