### ISSUE TITLE
Demos not working on certain Aurelia Hub routes

### ISSUE THREAD

**Issue by deviprsd21** [aurelia/documentation#309]
The demos of this page [Converters](http://aurelia.io/hub.html#/doc/article/aurelia/binding/latest/binding-value-converters/3) is not working. 

Console shows this error 
```console
Unhandled rejection TypeError: moment is not a function
    at DateFormatValueConverter.toView (https://cdn.rawgit.com/aurelia/binding/1.0.9/doc/example-dist/binding-value-converters/simple-converter/date-format.js:40:14)
    at t.e.ValueConverter.t.evaluate (http://aurelia.io/scripts/vendor-bundle.js:6:20979)
    at e.ChildInterpolationBinding.e.bind (http://aurelia.io/scripts/vendor-bundle.js:14:23552)
    at e.View.e.bind (http://aurelia.io/scripts/vendor-bundle.js:13:7799)
    at e.Controller.e.bind (http://aurelia.io/scripts/vendor-bundle.js:13:29578)
    at e.Controller.e.automate (http://aurelia.io/scripts/vendor-bundle.js:13:28838)
    at http://aurelia.io/scripts/vendor-bundle.js:14:10133
```

**Comment by AStoker** [comment]
Make sure you have `moment` installed with npm, and that you've defined it as a dependency in your vendor bundle.

**Comment by deviprsd21** [comment]
No this is a bug in aurelia.io, I'm reporting it

**Comment by AStoker** [comment]
Oops! My bad, yup, that's broke all right 😄

**Comment by deviprsd21** [comment]
Moment is included in the file, why is there an error then?

**Comment by AStoker** [comment]
Moment seems to be the Moment instance, not a function

**Comment by deviprsd21** [comment]
The [official docs]( http://momentjs.com/docs/#/use-it/typescript/) suggest this

```javascript
import * as moment from 'moment';

let now = moment().format('LLLL');
```

**Comment by AStoker** [comment]
Somebody is on it, they've got a backlog of things to do over the weekend, and this is one of them.

**Comment by deviprsd21** [comment]
Okay 👍

**Comment by jdanyow** [comment]
https://github.com/aurelia/binding/issues/504
