### ISSUE TITLE
IE11: Left-hand menu doesn't appear

### ISSUE THREAD

**Issue by marksummerfield** [aurelia/documentation#322]
I'm on Windows 7, IE 11.0.9600.18537.

![image](https://cloud.githubusercontent.com/assets/6152717/22215336/e31b25f2-e192-11e6-8aca-9bb0a0269744.png)

I've attached a screenshot. It looks like IE has decided that the nav has height 0. The menu html is present in Developer Tools and there are no errors in the Console log. I've also checked the Emulation and I'm on 'Edge (Default)' with all the other settings at the usual defaults.

**Comment by atsu85** [comment]
I can confirm it.
Guick look at the stack trace is hinting, it could be related to animation:
```
Unhandled rejection TypeError: Object doesn't support this action
   at Anonymous function (http://aurelia.io/scripts/app-bundle.js:4:1990)
   at e.prototype.animate (http://aurelia.io/scripts/app-bundle.js:4:1959)
   at e.prototype._animateElement (http://aurelia.io/scripts/app-bundle.js:4:339)
   at e.prototype.enter (http://aurelia.io/scripts/app-bundle.js:4:507)
   at e.prototype.animateView (http://aurelia.io/scripts/vendor-bundle.js:13:10036)
   at e.prototype.attached (http://aurelia.io/scripts/vendor-bundle.js:13:13068)
   at e.prototype.attached (http://aurelia.io/scripts/vendor-bundle.js:13:9227)
From previous event:
   at e.prototype.setRoot (http://aurelia.io/scripts/vendor-bundle.js:9:18852)
   at Anonymous function (http://aurelia.io/scripts/app-bundle.js:1:4206)
From previous event:
   at r (http://aurelia.io/scripts/app-bundle.js:1:4179)
   at Anonymous function (http://aurelia.io/scripts/vendor-bundle.js:9:7681)
From previous event:
   at u (http://aurelia.io/scripts/vendor-bundle.js:9:7507)
```

**Comment by Alexander-Taran** [comment]
can be closed.
new docs run fine in IE 11
