### ISSUE TITLE
JavaScript error on various aurelia.io dochub pages

### ISSUE THREAD

**Issue by thinkOfaNumber** [aurelia/documentation#334]
**I'm submitting a bug report**

* **Library Version:**
Current instance published to http://aurelia.io/hub.html

**Please tell us about your environment:**
Windows 7
Chrome Version 56.0.2924.87 (64-bit)
Internet Explorer 11.0.9600.18617

**Current behavior:**
Sorry if this is not the right place for reporting this. I've tried multiple Windows 7 computers, with Chrome and IE. I've only noticed this error today (have visited the dochub extensively lately).

Visit the doc hub page: http://aurelia.io/hub.html#/doc/article/aurelia/templating/latest/templating-content-projection/4

there is a JavaScript error:
`Unhandled rejection TypeError: Cannot read property 'code' of undefined
    at e.CodeListing.e.select (http://aurelia.io/scripts/app-bundle.js:3:22729)
    at e.CodeListing.e.selectSourceForLanguage (http://aurelia.io/scripts/app-bundle.js:3:22627)
    at e.CodeListing.e.bind (http://aurelia.io/scripts/app-bundle.js:3:21584)
    at e.View.e.bind (http://aurelia.io/scripts/vendor-bundle.js:13:7845)
    at e.Controller.e.bind (http://aurelia.io/scripts/vendor-bundle.js:13:29578)
    at e.View.e.bind (http://aurelia.io/scripts/vendor-bundle.js:13:7995)
    at e.Controller.e.bind (http://aurelia.io/scripts/vendor-bundle.js:13:29578)
    at e.Controller.e.automate (http://aurelia.io/scripts/vendor-bundle.js:13:28838)
    at http://aurelia.io/scripts/vendor-bundle.js:14:10133`

Various dochub pages seem to have the error, but some don't.

**Comment by EisenbergEffect** [comment]
Closing as a duplicate. We're aware there is something wrong with that article and are looking into it. Thanks!

**Comment by thinkOfaNumber** [comment]
No problems, in general is this the right place to report website issues? Thanks.

**Comment by EisenbergEffect** [comment]
Yes sir :)
